refactor!: Implement `send_notification` function
Cleans up multiline calls to `notify-send`
Fixed indentation of "crashed" if statement
Lowercased local variables

diff --git a/winexec b/winexec
--- a/winexec
+++ b/winexec
@@ -14,196 +14,155 @@ readonly EC_NOT_EXIST=6
 
 readonly VM_NAME='win11'
 
-exit_with_error() {
-  local -i ERR_CODE="$1"
+send_notification() {
+  # Declare variables
+  local message="$1"
+  local -i duration="${2:-3}"
+
+  # Read from stdin if `message` is unset
+  if [[ -z "${message}" ]]; then
+    while IFS= read -r line; do
+      message+="${line}"
+    done
+  fi
+
+  # Convert to milliseconds
+  (( duration *= 1000 ))
   
-  case "${ERR_CODE}" in
+  notify-send --expire-time="${duration}" --urgency='low' 'Windows' "${message}"
+}
+
+exit_with_error() {
+  # Declare error code variable
+  local -i err_code="$1"
+  
+  # Notify user of specific error
+  case "${err_code}" in
     "${EC_FAIL_START}")
-      notify-send \
-        --expire-time=8000 \
-        --urgency='low' \
-        'Windows' \
-        'The virtual machine failed to start.'
+      send_notification 'The virtual machine failed to start.' '8'
       ;;
     "${EC_FAIL_RESUME}")
-      notify-send \
-        --expire-time=8000 \
-        --urgency='low' \
-        'Windows' \
-        'The virtual machine failed to resume.'
+      send_notification 'The virtual machine failed to resume.' '8'
       ;;
     "${EC_FAIL_DESTROY}")
-      notify-send \
-        --expire-time=8000 \
-        --urgency='low' \
-        'Windows' \
-        'The virtual machine failed to shut down forcefully.'
+      send_notification \
+        'The virtual machine failed to shut down forcefully.' \
+        '8'
       ;;
     "${EC_SD_TIMEOUT}")
-      notify-send \
-        --expire-time=8000 \
-        --urgency='low' \
-        'Windows' \
-        'The virtual machine took too long to shut down.'
+      send_notification 'The virtual machine took too long to shut down.' '8'
       ;;
     "${EC_DIE_TIMEOUT}")
-      notify-send \
-        --expire-time=8000 \
-        --urgency='low' \
-        'Windows' \
-        'The virtual machine took too long to die.'
+      send_notification 'The virtual machine took too long to die.' '8'
       ;;
     "${EC_NOT_EXIST}")
-      notify-send \
-        --expire-time=8000 \
-        --urgency='low' \
-        'Windows' \
-        'The virtual machine does not exist.'
+      send_notification 'The virtual machine does not exist.' '8'
       ;;
   esac
 
   # Terminate the script
-  exit "${ERR_CODE}"
+  exit "${err_code}"
 }
 
 is_vm_running() {
   # Declare exit status variable
-  local -i EXIT_STATUS=0
+  local -i exit_status=0
 
   # Declare timer variables
-  local -i TIME_ELAPSED=0
-  local -i TIME_LIMIT=60
-  local -i TIME_INTERVAL=5
+  local -i time_elapsed=0
+  local -i time_limit=60
+  local -i time_interval=5
 
   # Attempt to start Windows VM
   if (virsh list --all --name | xargs | grep -wq "${VM_NAME}"); then
     if (virsh list --state-shutoff --name | xargs | grep -wq "${VM_NAME}"); then
-      notify-send \
-        --expire-time=3000 \
-        --urgency='low' \
-        'Windows' \
-        'Booting the virtual machine.'
-      virsh start "${VM_NAME}" &>/dev/null || EXIT_STATUS="${EC_FAIL_START}"
+      send_notification 'Booting the virtual machine.'
+      virsh start "${VM_NAME}" &>/dev/null || exit_status="${EC_FAIL_START}"
       if (virsh list --state-paused --name \
         | xargs \
         | grep -wq "${VM_NAME}"); then
-        notify-send \
-          --expire-time=3000 \
-          --urgency='low' \
-          'Windows' \
-          'Resuming the virtual machine.'
-        virsh resume "${VM_NAME}" &>/dev/null || EXIT_STATUS="${EC_FAIL_RESUME}"
+        send_notification 'Resuming the virtual machine.'
+        virsh resume "${VM_NAME}" &>/dev/null || exit_status="${EC_FAIL_RESUME}"
       fi
     elif (virsh list --state-paused --name \
       | xargs \
       | grep -wq "${VM_NAME}"); then
-      notify-send \
-        --expire-time=3000 \
-        --urgency='low' \
-        'Windows' \
-        'Resuming the virtual machine.'
-      virsh resume "${VM_NAME}" &>/dev/null || EXIT_STATUS="${EC_FAIL_RESUME}"
+      send_notification 'Resuming the virtual machine.'
+      virsh resume "${VM_NAME}" &>/dev/null || exit_status="${EC_FAIL_RESUME}"
     elif (virsh list --state-other --name | xargs | grep -wq "${VM_NAME}"); then
       if (virsh domstate "${VM_NAME}" | xargs | grep -wq 'shutdown'); then
-        notify-send \
-          --expire-time=3000 \
-          --urgency='low' \
-          'Windows' \
-          'The virtual machine is currently shutting down.\n'\
-          'It will automatically restart once the shutdown process is complete.'
-        EXIT_STATUS="${EC_SD_TIMEOUT}"
-        while (( TIME_ELAPSED < TIME_LIMIT )); do
+        send_notification '' '' <<-END
+					The virtual machine is currently shutting down.\n
+					It will automatically restart once the shutdown process is complete.
+				END
+        exit_status="${EC_SD_TIMEOUT}"
+        while (( time_elapsed < time_limit )); do
           if (virsh list --state-shutoff --name \
             | xargs \
             | grep -wq "${VM_NAME}"); then
-            EXIT_STATUS=0
-            notify-send \
-              --expire-time=3000 \
-              --urgency='low' \
-              'Windows' \
-              'Booting the virtual machine.'
+            exit_status=0
+            send_notification 'Booting the virtual machine.'
             virsh start "${VM_NAME}" &>/dev/null ||
-              EXIT_STATUS="${EC_FAIL_START}"
+              exit_status="${EC_FAIL_START}"
             break
           fi
-          sleep "${TIME_INTERVAL}"
-          TIME_ELAPSED="$((TIME_ELAPSED + TIME_INTERVAL))"
+          sleep "${time_interval}"
+          (( time_elapsed += time_interval ))
         done
       elif (virsh domstate "${VM_NAME}" | xargs | grep -wq 'crashed'); then
-        notify-send \
-          --expire-time=3000 \
-          --urgency='low' \
-          'Windows' \
-          'The virtual machine experienced an unexpected crash.\n'\
-          'Attempting to restart.'
+        send_notification '' '' <<-END
+					The virtual machine experienced an unexpected crash.\n
+					Attempting to restart.
+				END
         virsh destroy "${VM_NAME}" &>/dev/null ||
-          EXIT_STATUS="${EC_FAIL_DESTROY}"
-        if (( EXIT_STATUS == 0 )); then
-          notify-send \
-            --expire-time=3000 \
-            --urgency='low' \
-            'Windows' \
-            'Booting the virtual machine.'
-          virsh start "${VM_NAME}" &>/dev/null || EXIT_STATUS="${EC_FAIL_START}"
+          exit_status="${EC_FAIL_DESTROY}"
+        if (( exit_status == 0 )); then
+          send_notification 'Booting the virtual machine.'
+          virsh start "${VM_NAME}" &>/dev/null || exit_status="${EC_FAIL_START}"
         fi
       elif (virsh domstate "${VM_NAME}" | xargs | grep -wq 'dying'); then
-        notify-send \
-          --expire-time=3000 \
-          --urgency='low' \
-          'Windows' \
-          'The virtual machine is currently shutting down unexpectedly.\n'\
-          'It will try to restart once the shutdown process finishes.'
-        EXIT_STATUS="${EC_DIE_TIMEOUT}"
-        while (( TIME_ELAPSED < TIME_LIMIT )); do
+        send_notification '' '' <<-END
+					The virtual machine is currently shutting down unexpectedly.\n
+					It will try to restart once the shutdown process finishes.
+				END
+        exit_status="${EC_DIE_TIMEOUT}"
+        while (( time_elapsed < time_limit )); do
           if (virsh domstate "${VM_NAME}" | xargs | grep -wq 'crashed'); then
-            EXIT_STATUS=0
-            notify-send \
-              --expire-time=3000 \
-              --urgency='low' \
-              'Windows' \
-              'The virtual machine experienced an unexpected crash.\n'\
-              'Attempting to restart.'
-              virsh destroy "${VM_NAME}" &>/dev/null ||
-                EXIT_STATUS="${EC_FAIL_DESTROY}"
-              if (( EXIT_STATUS == 0 )); then
-                notify-send \
-                  --expire-time=3000 \
-                  --urgency='low' \
-                  'Windows' \
-                  'Booting the virtual machine.'
-                virsh start "${VM_NAME}" &>/dev/null ||
-                  EXIT_STATUS="${EC_FAIL_START}"
-              fi
-              break
-            elif (virsh list --state-shutoff --name \
-              | xargs \
-              | grep -wq "${VM_NAME}"); then
-              EXIT_STATUS=0
-              notify-send \
-                --expire-time=3000 \
-                --urgency='low' \
-                'Windows' \
-                'Booting the virtual machine.'
+            exit_status=0
+            send_notification '' '' <<-END
+							The virtual machine experienced an unexpected crash.\n
+							Attempting to restart.
+						END
+            virsh destroy "${VM_NAME}" &>/dev/null ||
+              exit_status="${EC_FAIL_DESTROY}"
+            if (( exit_status == 0 )); then
+              send_notification 'Booting the virtual machine.'
               virsh start "${VM_NAME}" &>/dev/null ||
-                EXIT_STATUS="${EC_FAIL_START}"
-              break
+                exit_status="${EC_FAIL_START}"
             fi
-            sleep "${TIME_INTERVAL}"
-            TIME_ELAPSED="$((TIME_ELAPSED + TIME_INTERVAL))"
-          done
-        elif (virsh domstate "${VM_NAME}" \
-          | xargs \
-          | grep -wq 'pmsuspended'); then
-          virsh resume "${VM_NAME}" &>/dev/null ||
-            EXIT_STATUS="${EC_FAIL_RESUME}"
-        fi
+            break
+          elif (virsh list --state-shutoff --name \
+            | xargs \
+            | grep -wq "${VM_NAME}"); then
+            exit_status=0
+            send_notification 'Booting the virtual machine.'
+            virsh start "${VM_NAME}" &>/dev/null ||
+              exit_status="${EC_FAIL_START}"
+            break
+          fi
+          sleep "${time_interval}"
+          (( time_elapsed += time_interval ))
+        done
+      elif (virsh domstate "${VM_NAME}" | xargs | grep -wq 'pmsuspended'); then
+        virsh resume "${VM_NAME}" &>/dev/null || exit_status="${EC_FAIL_RESUME}"
       fi
-    else
-      EXIT_STATUS="${EC_NOT_EXIST}"
     fi
+  else
+    exit_status="${EC_NOT_EXIST}"
+  fi
 
-    # Handle non-zero exit status
-    (( EXIT_STATUS != 0)) && exit_with_error "${EXIT_STATUS}"
+  # Handle non-zero exit status
+  (( exit_status != 0)) && exit_with_error "${exit_status}"
 }
 
 is_vm_running
